### ISSUE TITLE
메인 이미지 처리

### ISSUE THREAD

**Issue by joyjhm** [Canvas-Diary/Backend#12]
- 현재 일기 단건 조회 시 image List 첫번째 Image를 대표 이미지로 판단하도록 하였음.
- 이미지를 시간순으로 나열해 전달 후 조회 시 대표 이미지를 보여주도록 하는 것이 어떠하냐는 의견이 있음.

**Comment by kch1015** [comment]
Image 도메인에 isMain 속성 추가로 해결
