### ISSUE TITLE
단순 일기 내용 수정 엔드포인트 추가

### ISSUE THREAD

**Issue by joyjhm** [Canvas-Diary/Backend#69]
현재 일기 수정 시 화풍 선택, 공개 비공개 선택하고 일기 내용이 수정되어 그림이 다시 그려지도록 되어 있는데 간단하게 일기 내용만 수정할 수 있는 앤드포인트도 추가해야 한다.

**Comment by kch1015** [comment]
- #98 

일기 수정 시 내용만 수정하고 그림을 그리지 않도록 수정
그림을 다시 그리고 싶으면 내용 수정 후 이미지를 추가하거나, 일기 삭제 후 재생성으로 대체
